from backend.config import settings


def generate_demo_document(
    document_type,
    parties,
    terms,
    effective_date,
    jurisdiction,
    language,
    company_name,
):
    return f"""DEMO LEGAL DOCUMENT

Document Type: {document_type}
Company Name: {company_name}
Parties: {parties}
Terms: {terms}
Effective Date: {effective_date}
Jurisdiction: {jurisdiction}
Language: {language}

This is a demo document generated by LegalEase.
It is not legal advice and should be reviewed by a qualified professional.
"""


def generate_with_gemini(
    document_type,
    parties,
    terms,
    effective_date,
    jurisdiction,
    language,
    company_name,
    additional_instructions,
):
    if not settings.gemini_api_key:
        raise ValueError(
            "Gemini API key is not configured. "
            "Please add GEMINI_API_KEY to your .env file."
        )

    try:
        from google import genai
        from google.genai import types

        client = genai.Client(
            api_key=settings.gemini_api_key
        )

        prompt = f"""
Create a professional legal document for the LegalEase application.

Document Type:
{document_type}

Company Name:
{company_name}

Parties:
{parties}

Terms:
{terms}

Effective Date:
{effective_date}

Jurisdiction:
{jurisdiction}

Language:
{language}

Additional Instructions:
{additional_instructions}

Requirements:
- Generate only the legal document content.
- Use clear and professional legal language.
- Organize the document with appropriate headings and clauses.
- Do not invent personal information.
- If required information is missing, use clear placeholders.
- Include signature sections where appropriate.
- Do not provide legal advice outside the document.
- Make the document suitable for editing and export.
"""

        response = client.models.generate_content(
            model=settings.gemini_model,
            contents=prompt,
            config=types.GenerateContentConfig(
                max_output_tokens=6000,
                thinking_config=types.ThinkingConfig(
                    thinking_level="low"
                ),
            ),
        )

        if not response.text:
            raise RuntimeError(
                "Gemini returned an empty response."
            )

        return response.text

    except ImportError:
        raise RuntimeError(
            "Google GenAI package is not installed. "
            "Run: pip install -U google-genai"
        )