from io import BytesIO


def format_txt(document: str, company_name: str = "LegalEase") -> bytes:
    return document.encode("utf-8")


def format_docx(document: str, company_name: str = "LegalEase") -> bytes:
    from docx import Document
    from docx.shared import Pt

    doc = Document()

    if company_name:
        heading = doc.add_heading(company_name, level=1)
        heading.alignment = 1

    for paragraph in document.split("\n"):
        p = doc.add_paragraph(paragraph)

        for run in p.runs:
            run.font.name = "Times New Roman"
            run.font.size = Pt(12)

    section = doc.sections[0]
    footer = section.footer
    footer_paragraph = footer.paragraphs[0]

    footer_paragraph.text = f"{company_name} | Generated by LegalEase"

    for run in footer_paragraph.runs:
        run.font.name = "Times New Roman"
        run.font.size = Pt(9)

    output = BytesIO()
    doc.save(output)
    output.seek(0)

    return output.getvalue()


def format_pdf(document: str, company_name: str = "LegalEase") -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.pdfgen import canvas
    from reportlab.pdfbase.pdfmetrics import stringWidth

    output = BytesIO()
    pdf = canvas.Canvas(output, pagesize=A4)

    width, height = A4
    left_margin = 50
    right_margin = 50
    top_margin = 50
    bottom_margin = 50

    usable_width = width - left_margin - right_margin
    y = height - top_margin

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawCentredString(width / 2, y, company_name)

    y -= 30
    pdf.setFont("Helvetica", 10)

    for paragraph in document.split("\n"):

        if not paragraph.strip():
            y -= 15
            continue

        words = paragraph.split()
        current_line = ""

        for word in words:
            test_line = (
                word
                if not current_line
                else current_line + " " + word
            )

            if stringWidth(
                test_line,
                "Helvetica",
                10
            ) <= usable_width:
                current_line = test_line
            else:
                pdf.drawString(
                    left_margin,
                    y,
                    current_line
                )

                y -= 15

                if y < bottom_margin:
                    pdf.showPage()
                    y = height - top_margin
                    pdf.setFont("Helvetica", 10)

                current_line = word

        if current_line:
            pdf.drawString(
                left_margin,
                y,
                current_line
            )
            y -= 15

        if y < bottom_margin:
            pdf.showPage()
            y = height - top_margin
            pdf.setFont("Helvetica", 10)

    pdf.setFont("Helvetica", 8)
    pdf.drawCentredString(
        width / 2,
        25,
        f"{company_name} | Generated by LegalEase"
    )

    pdf.save()
    output.seek(0)

    return output.getvalue()